name: Avesha Open Source
description: For Bugs Related to Avesha Open Source Installation
title: "Give a title to your Problem !!  "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
      
      
  - type: dropdown
    id: Chartname
    attributes:
      label: Chartname
      description: Select Open Source Chart, in which you are facing the issue ?
      options:
        - avesha/cert-manager
        - avesha/istio-base
        - avesha/istio-discovery
        - avesha/kubeslice-controller
        - avesha/kubeslice-worker
    validations:
      required: true
      
  - type: input
    id: ChartVersion
    attributes:
      label: Chart Version
      description: Tell us the Chart Version, in which you are facing the problem.
      placeholder: 0.0.0
    validations:
      required: true
      
  - type: dropdown
    id: Cloud
    attributes:
      label: Are you Doing Operation on cloud, if yes then which one ?
      description: you can choose multiple cloud, if you are using else just choose Local.
      multiple: true
      options:
        - Amazon Web Service
        - Azure Cloud
        - Google Cloud
        - Oracle CLoud
        - IBM Cloud
        - None of the above Cloud
        - Local
  
  - type: dropdown
    id: OS
    attributes:
      label: Tell us your operating System name ?
      description: you can choose multiple Operating System, if you are using.
      multiple: true
      options:
        - Ubuntu  OS
        - Mac     OS
        - Amazon  OS
        - Redhat  OS
        - Windows OS
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - None of the Above
        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of conduct. [ Visit Avesha for more info ](https://avesha.io)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
